# Generated by Django 2.0.9 on 2023-11-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineDressShop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
