# Generated by Django 2.0.9 on 2023-11-21 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineDressShop', '0002_order_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('account_no', models.CharField(max_length=200)),
                ('ifsc_code', models.CharField(max_length=200)),
                ('bankbalance', models.CharField(max_length=200)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='OnlineDressShop.login')),
            ],
        ),
    ]
